services:
  postgres:
    image: postgres:15-alpine
    container_name: b30_db
    environment:
      POSTGRES_DB: b30_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    volumes:
      - b30_postgres_data_v2:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: b30_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/b30_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "1234"
      JWT_SECRET: segredo_super_secreto_producao
    ports:
      - "8080:8080"
    restart: always

  prometheus:
      image: prom/prometheus:latest
      container_name: b30_prometheus
      restart: always
      ports:
        - "9090:9090"
      volumes:
        - ./src/main/java/com/said/B30/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      depends_on:
        - app

  grafana:
      image: grafana/grafana:latest
      container_name: b30_grafana
      restart: always
      ports:
         - "3000:3000"
      volumes:
        - grafana_data:/var/lib/grafana
      depends_on:
        - prometheus

volumes:
  b30_postgres_data_v2:
  grafana_data:
